import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import ExitAnimation from "@/components/ExitAnimation";
import { Suspense } from "react";
import EnterAnimation from "@/components/EnterAnimation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Suspense>
          <ExitAnimation />
        </Suspense>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
